// Generated by ReScript, PLEASE EDIT WITH CARE


function isValid(str) {
  return str.includes("@");
}

var Email = {
  isValid: isValid
};

function persist(user) {
  return new Promise((function (resolve, param) {
                setTimeout((function (param) {
                        return resolve(user);
                      }), 2000);
                
              }));
}

export {
  Email ,
  persist ,
  
}
/* No side effect */
