// Generated by ReScript, PLEASE EDIT WITH CARE


var emailRe = /^[^\s@]+@[^\s@]+$/;

function make(str) {
  if (emailRe.test(str)) {
    return str;
  }
  
}

var Email = {
  make: make
};

function persist(user) {
  return new Promise((function (resolve, param) {
                setTimeout((function (param) {
                        return resolve(user);
                      }), 2000);
                
              }));
}

export {
  Email ,
  persist ,
  
}
/* No side effect */
