// Generated by ReScript, PLEASE EDIT WITH CARE


var emailRe = /^[^\s@]+@[^\s@]+$/;

function isValid(str) {
  return emailRe.test(str);
}

var Email = {
  emailRe: emailRe,
  isValid: isValid
};

function persist(user) {
  return new Promise((function (resolve, param) {
                setTimeout((function (param) {
                        return resolve(user);
                      }), 2000);
                
              }));
}

export {
  Email ,
  persist ,
  
}
/* No side effect */
