// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Base from "./components/Base.js";
import * as React from "react";

function $$default(_props) {
  return React.createElement("div", undefined, React.createElement(Base.make, {}));
}

function getServerSideProps(_ctx) {
  return Promise.resolve({
              props: undefined
            });
}

export {
  $$default ,
  $$default as default,
  getServerSideProps ,
  
}
/* Base Not a pure module */
