// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Profile from "./Profile.js";

function $$default(param) {
  return React.createElement(Profile.make, {});
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
