// Generated by ReScript, PLEASE EDIT WITH CARE

import * as User from "./types/User.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Int from "bs-platform/lib/es6/belt_Int.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

var input = "px-2 py-2 border-2 rounded-md border-gray-200 focus:outline-none focus:ring-1 focus:ring-pink-300 focus:border-transparent";

var container = "flex flex-col shadow-xl";

var header = "py-6 px-14 bg-gradient-to-tr from-gray-500 to-yellow-600 rounded-tl-2xl rounded-tr-2xl text-center space-y-8";

var headerText = "text-white text-center font-bold text-xl";

var form = "flex flex-col py-6 px-8 space-y-5 bg-white";

var button = "w-full py-3 bg-yellow-500 text-black rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-pink-500 focus:border-transparent shadow-lg";

var Style = {
  input: input,
  container: container,
  header: header,
  headerText: headerText,
  form: form,
  button: button
};

function reducer(state, action) {
  if (action.TAG !== /* Update */0) {
    return {
            name: state.name,
            email: state.email,
            age: state.age,
            status: action._0
          };
  }
  switch (action._0) {
    case /* Name */0 :
        return {
                name: action._1,
                email: state.email,
                age: state.age,
                status: /* Edited */1
              };
    case /* Email */1 :
        return {
                name: state.name,
                email: action._1,
                age: state.age,
                status: /* Edited */1
              };
    case /* Age */2 :
        return {
                name: state.name,
                email: state.email,
                age: Belt_Option.getWithDefault(Belt_Int.fromString(action._1), 0),
                status: /* Edited */1
              };
    
  }
}

function updateField(dispatch, field, ev) {
  var value = ev.target.value;
  return Curry._1(dispatch, {
              TAG: 0,
              _0: field,
              _1: value,
              [Symbol.for("name")]: "Update"
            });
}

function Profile(Props) {
  var match = React.useReducer(reducer, {
        name: "",
        email: "",
        age: 0,
        status: /* Iddle */0
      });
  var dispatch = match[1];
  var state = match[0];
  var match$1 = React.useState(function () {
        
      });
  var setUser = match$1[1];
  var onChange = function (param, param$1) {
    return updateField(dispatch, param, param$1);
  };
  var onClick = function (param) {
    var match = state.status;
    var match$1 = User.make(state.name, state.age, state.email);
    if (match !== 1 || match$1 === undefined) {
      return ;
    } else {
      Curry._1(dispatch, {
            TAG: 1,
            _0: /* Saving */3,
            [Symbol.for("name")]: "SetStatus"
          });
      User.persist(Caml_option.valFromOption(match$1)).then(function (savedUser) {
            Curry._1(dispatch, {
                  TAG: 1,
                  _0: /* Saved */2,
                  [Symbol.for("name")]: "SetStatus"
                });
            Curry._1(setUser, (function (param) {
                    return Caml_option.some(savedUser);
                  }));
            return Promise.resolve(undefined);
          });
      return ;
    }
  };
  var match$2 = state.status;
  var match$3 = state.status;
  var tmp;
  if (match$3 !== 0) {
    switch (match$3) {
      case /* Edited */1 :
          tmp = "Save";
          break;
      case /* Saved */2 :
          tmp = "Saved";
          break;
      case /* Saving */3 :
          tmp = "Saving...";
          break;
      
    }
  } else {
    tmp = "Saved";
  }
  var match$4 = Belt_Option.map(match$1[0], User.view);
  var tmp$1;
  if (match$4 !== undefined) {
    var exit = 0;
    if (match$4.name === "mathieu" && match$4.age === 99) {
      tmp$1 = match$4.email === "mathieu@example.com" ? "You're an old Mathieu and you have a fake email" : "You're an old Mathieu";
    } else {
      exit = 1;
    }
    if (exit === 1) {
      tmp$1 = match$4.age !== 99 ? "Can't say what you are" : "You're an old user";
    }
    
  } else {
    tmp$1 = "Can't say what you are";
  }
  return React.createElement("div", {
              className: container
            }, React.createElement("div", {
                  className: header
                }, React.createElement("h2", {
                      className: headerText
                    }, "Profile form")), React.createElement("div", {
                  className: form
                }, React.createElement("input", {
                      className: input,
                      placeholder: "Enter your name",
                      type: "text",
                      value: state.name,
                      onChange: (function (param) {
                          return onChange(/* Name */0, param);
                        })
                    }), React.createElement("input", {
                      className: input,
                      placeholder: "Enter your email",
                      type: "email",
                      value: state.email,
                      onChange: (function (param) {
                          return onChange(/* Email */1, param);
                        })
                    }), React.createElement("input", {
                      className: input,
                      type: "number",
                      value: String(state.age),
                      onChange: (function (param) {
                          return onChange(/* Age */2, param);
                        })
                    }), React.createElement("button", {
                      className: button,
                      disabled: match$2 !== 1,
                      onClick: onClick
                    }, tmp)), tmp$1);
}

var make = Profile;

var $$default = Profile;

export {
  Style ,
  reducer ,
  updateField ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
